config/routes.rb
Rails.application.routes.draw do
  
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'
 # pages controller
  root 'pages#home'
  get 'about', to: 'pages#about'
  
 # article Controller
  resources :articles

 #sessions 
 get 'signup', to: 'users#new'

 get 'login', to: 'sessions#new'
 post'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'


 resources :categories, except: [:destroy]

 #post 'users', to: 'users#create'

 #users controller
 resources :users, except: [:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :requrie_admin, except: [:index,:show]

	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
		
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path

		else
			render 'new'
		end
	end

	def show
		@category = Category.find(params[:id])
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success] = "Category name was successfully updated"
			redirect_to category_path(@category)
		else
			render 'new'
		end		
	end

	private 
	def category_params
		params.require(:category).permit(:name)
		
	end
	def requrie_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:danger] = "only admins can perform that action"
			redirect_to categories_path
		end
	end
end

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name, category_path(category) %> &nbsp;   </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>


<%= form_with(model: @category, local: true, :html => {class: "form-horizontal", role: "form"}) do |form| %>
  <div class="form-group">
    <div class="control-label col-sm-2"> 
      <%= form.label :name %>
    </div>

    <div class="col-sm-8">
      <%= form.text_field :name, class: "form-control",  placeholder: "Enter category name", autofocus: true%>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to 'Cancel request and return view articles', articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit	category name</h1>
<%= render 'form'%>

app/views/categories/index.html.erb
<h1 align="center">Listing	All  Categories</h1>

<div align="center">
	<%= will_paginate %>

	<% @categories.each  do |category| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li class="article-title">
						<%= link_to "#{category.name}", category_path(category) %>
					</li>
					<li><small> <%= pluralize(category.articles.count, "article")%></small></li>
				</div>
			</div>	

		</ul>
	<% end %>
	<%= will_paginate %>

</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>
<%= render 'form'%>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: "+ @category.name %></h1>

<div align="center">
	<% if logged_in? and current_user.admin? %>
	<div class="row">
		<span class="badge"> <%= link_to "Edit Category Name ", edit_category_path(@category) %></span>
	</div>
	<%end%>

  <%= will_paginate @category_articles%>
</div>
<%= render 'articles/article', obj: @category_articles%>

<div align="center">
  <%= will_paginate @category_articles %>
</div>